SET IDENTITY_INSERT [dbo].[Users] ON
INSERT INTO [dbo].[Users] ([Id], [FirstName], [LastName], [EmailAddress], [MobileNumber], [AlternativeNumber], [NationalId], [ProfilePhotoUrl], [IsActive], [GenderId], [UserStatusId], [RoleId], [PropertyId], [CreatedBy], [CreatedOn], [UpdatedBy], [UpdatedOn], [ApplicationUserId]) VALUES (70, N'major', N'nganga', N'lazepak6@gmail.com', N'0796785827', NULL, NULL, NULL, 0, NULL, 21, 1, NULL, NULL, N'2025-12-22 09:01:15', NULL, NULL, 7)
INSERT INTO [dbo].[Users] ([Id], [FirstName], [LastName], [EmailAddress], [MobileNumber], [AlternativeNumber], [NationalId], [ProfilePhotoUrl], [IsActive], [GenderId], [UserStatusId], [RoleId], [PropertyId], [CreatedBy], [CreatedOn], [UpdatedBy], [UpdatedOn], [ApplicationUserId]) VALUES (71, N'trial002', N'002', N'trial002@gmail.com', N'0555444444', NULL, NULL, NULL, 0, NULL, 21, 1, NULL, NULL, N'2025-12-30 10:46:33', NULL, NULL, 8)
INSERT INTO [dbo].[Users] ([Id], [FirstName], [LastName], [EmailAddress], [MobileNumber], [AlternativeNumber], [NationalId], [ProfilePhotoUrl], [IsActive], [GenderId], [UserStatusId], [RoleId], [PropertyId], [CreatedBy], [CreatedOn], [UpdatedBy], [UpdatedOn], [ApplicationUserId]) VALUES (72, N'test004', N'string', N'test4@gmail.com', N'string', NULL, NULL, NULL, 0, NULL, 21, 1, NULL, NULL, N'2025-12-30 22:28:10', NULL, NULL, 9)
INSERT INTO [dbo].[Users] ([Id], [FirstName], [LastName], [EmailAddress], [MobileNumber], [AlternativeNumber], [NationalId], [ProfilePhotoUrl], [IsActive], [GenderId], [UserStatusId], [RoleId], [PropertyId], [CreatedBy], [CreatedOn], [UpdatedBy], [UpdatedOn], [ApplicationUserId]) VALUES (73, N'string', N'string', N'string@gmail.com', N'string', NULL, NULL, NULL, 0, NULL, 21, 1, NULL, NULL, N'2025-12-30 23:17:02', NULL, NULL, 10)
INSERT INTO [dbo].[Users] ([Id], [FirstName], [LastName], [EmailAddress], [MobileNumber], [AlternativeNumber], [NationalId], [ProfilePhotoUrl], [IsActive], [GenderId], [UserStatusId], [RoleId], [PropertyId], [CreatedBy], [CreatedOn], [UpdatedBy], [UpdatedOn], [ApplicationUserId]) VALUES (74, N'Major', N'Lazer', N'lazer@gmail.com', N'0718317726', NULL, NULL, NULL, 0, NULL, 21, 3, NULL, NULL, N'2026-01-10 16:01:07', NULL, NULL, 13)
INSERT INTO [dbo].[Users] ([Id], [FirstName], [LastName], [EmailAddress], [MobileNumber], [AlternativeNumber], [NationalId], [ProfilePhotoUrl], [IsActive], [GenderId], [UserStatusId], [RoleId], [PropertyId], [CreatedBy], [CreatedOn], [UpdatedBy], [UpdatedOn], [ApplicationUserId]) VALUES (75, N'Simon', N'Simon', N'simon@gmail.com', N'0718317726', N'', 0, NULL, 0, 4, 13, 6, 35, NULL, N'2026-01-14 18:42:48', NULL, NULL, 14)
INSERT INTO [dbo].[Users] ([Id], [FirstName], [LastName], [EmailAddress], [MobileNumber], [AlternativeNumber], [NationalId], [ProfilePhotoUrl], [IsActive], [GenderId], [UserStatusId], [RoleId], [PropertyId], [CreatedBy], [CreatedOn], [UpdatedBy], [UpdatedOn], [ApplicationUserId]) VALUES (76, N'Janet', N'Janet', N'janet@gmail.com', N'0718317726', N'', 0, NULL, 0, 5, 13, 6, 35, NULL, N'2026-01-15 08:09:08', NULL, NULL, 15)
INSERT INTO [dbo].[Users] ([Id], [FirstName], [LastName], [EmailAddress], [MobileNumber], [AlternativeNumber], [NationalId], [ProfilePhotoUrl], [IsActive], [GenderId], [UserStatusId], [RoleId], [PropertyId], [CreatedBy], [CreatedOn], [UpdatedBy], [UpdatedOn], [ApplicationUserId]) VALUES (77, N'tenant', N'tenant', N'tenant@gmail.com', N'0718317726', N'', 0, NULL, 0, 4, 13, 6, 35, NULL, N'2026-01-15 08:28:57', NULL, NULL, 16)
INSERT INTO [dbo].[Users] ([Id], [FirstName], [LastName], [EmailAddress], [MobileNumber], [AlternativeNumber], [NationalId], [ProfilePhotoUrl], [IsActive], [GenderId], [UserStatusId], [RoleId], [PropertyId], [CreatedBy], [CreatedOn], [UpdatedBy], [UpdatedOn], [ApplicationUserId]) VALUES (78, N'Jane', N'Jane', N'jane@gmai.com', N'0718317726', N'', 0, NULL, 0, 5, 13, 6, 35, NULL, N'2026-01-15 11:20:39', NULL, NULL, 17)
INSERT INTO [dbo].[Users] ([Id], [FirstName], [LastName], [EmailAddress], [MobileNumber], [AlternativeNumber], [NationalId], [ProfilePhotoUrl], [IsActive], [GenderId], [UserStatusId], [RoleId], [PropertyId], [CreatedBy], [CreatedOn], [UpdatedBy], [UpdatedOn], [ApplicationUserId]) VALUES (79, N'Stephen', N'Stephen', N'steve@gmail.com', N'0718317726', N'', 0, NULL, 0, 4, 13, 6, 35, NULL, N'2026-01-18 11:03:13', NULL, NULL, 18)
SET IDENTITY_INSERT [dbo].[Users] OFF
